language: objective-c
osx_image: xcode10.2
xcode_project: VideoTester.xcworkspace
xcode_scheme: VideoTester
script: xcrun xcodebuild test -workspace VideoTester.xcworkspace  -scheme VideoTester -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2'